config/routes.rb
Rails.application.routes.draw do
  root "my_threads#index"
  resources :my_threads do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :my_thread
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show 
    @comment = Comment.find(params[:my_thread_id])
  end 
  def new
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = Comment.new
  end

  def create
    @my_thread = MyThread.find(params[:my_thread_id])
    comment = @my_thread.comments.new(comment_params)
    if comment.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = @my_thread.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update!(comment_params)
    redirect_to root_path
  end 
  # def update
  #   @my_thread = MyThread.find(params[:my_thread_id])
  #   @comment = @my_thread.comments.find(params[:id])
  #   @comment.update(update_params)
  #   redirect_to root_path
  #   # if @comment.update(comment_params)
  #   #   flash[:success] = "Comment updated"
  #   #   redirect_to root_path
  #   # else
  #   #   flash[:danger] = "Comment failed"
  #   #   render 'edit'
  #   # end
  # end 

  def destroy
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = @my_thread.comments.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end
  private
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: %i[ show edit update destroy ]

  # GET /my_threads or /my_threads.json
  def index
    @my_threads = MyThread.all
  end

  # GET /my_threads/1 or /my_threads/1.json
  def show
    @my_thread = MyThread.find(params[:id])
  end

  # GET /my_threads/new
  def new
    @my_thread = MyThread.new
  end

  # GET /my_threads/1/edit
  def edit
  end

  # POST /my_threads or /my_threads.json
  def create
    @my_thread = MyThread.new(my_thread_params)

    respond_to do |format|
      if @my_thread.save
        format.html { redirect_to my_thread_url(@my_thread), notice: "My thread was successfully created." }
        format.json { render :show, status: :created, location: @my_thread }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_threads/1 or /my_threads/1.json
  def update
    respond_to do |format|
      if @my_thread.update(my_thread_params)
        format.html { redirect_to my_thread_url(@my_thread), notice: "My thread was successfully updated." }
        format.json { render :show, status: :ok, location: @my_thread }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_threads/1 or /my_threads/1.json
  def destroy
    @my_thread.destroy

    respond_to do |format|
      format.html { redirect_to my_threads_url, notice: "My thread was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_thread
      @my_thread = MyThread.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_thread_params
      params.require(:my_thread).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [:my_thread,comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this my_thread from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Create Comment</h1>
<%= render "form", comment:@comment %>

<br>

<div>
  <%= link_to "Back to my threads", my_threads_path %>
</div>

app/views/comments/new.html.erb
<h1>Create Comment</h1>
<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to my threads", my_threads_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread) do |form| %>
  <% if my_thread.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(my_thread.errors.count, "error") %> prohibited this my_thread from being saved:</h2>

      <ul>
        <% my_thread.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/my_threads/_my_thread.html.erb
<div id="<%= dom_id my_thread %>">
  <p>
    <strong>Title:</strong>
    <%= my_thread.title %>
  </p>

</div>

app/views/my_threads/edit.html.erb
<h1>Editing my thread</h1>

<%= render "form", my_thread: @my_thread %>

<br>

<div>
  <%= link_to "Show this my thread", @my_thread %> |
  <%= link_to "Back to my threads", my_threads_path %>
</div>

app/views/my_threads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>My threads</h1>

<div id="my_threads">
  <% @my_threads.each do |my_thread| %>
    <%= render my_thread %>
    <p>
      <%= link_to "Show this my thread", my_thread %>
    </p>
  <% end %>
</div>

<%= link_to "New my thread", new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>New my thread</h1>

<%= render "form", my_thread: @my_thread %>

<br>

<div>
  <%= link_to "Back to my threads", my_threads_path %>
</div>

app/views/my_threads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @my_thread %>

<div>
  <%= link_to "Edit this my thread", edit_my_thread_path(@my_thread) %> |
  <%= link_to "Back to my threads", my_threads_path %>

  <%= button_to "Destroy this my thread", @my_thread, method: :delete %>

  <%= link_to "New Comment", new_my_thread_comment_path(@my_thread) %>
  <% if @my_thread.comments.any? %>
  <ul>
    <% @my_thread.comments.each do |comment| %>
    <li>
      <%= comment.text%>
      <%= link_to "消去", my_thread_comment_path(@my_thread,comment), method: :delete, form: {data: { turbo_confirm: 'Sure?' }} %>
      <%= link_to "編集", edit_my_thread_comment_path(@my_thread, comment)%>
    </li>
    <% end %>
  </ul>
  <% end %>

</div>